# name: Publish docs via GitHub Pages
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: Deploy docs
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout main
#         uses: actions/checkout@v3

#       - name: Deploy docs
#         uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
#         # mhausenblas/mkdocs-deploy-gh-pages@master for material theme
#         # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           #CUSTOM_DOMAIN: optionaldomain.com
#           #CONFIG_FILE: folder/mkdocs.yml
#           EXTRA_PACKAGES: build-base
#           # GITHUB_DOMAIN: github.myenterprise.com

name: Publish docs via GitHub Pages 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
